"""Iteration 1 only: grammar -> LLM -> Hypothesis strategy -> sanity check.

    python -m fuzzer.seed_run --dry-run     # show the prompt, spend nothing
    python -m fuzzer.seed_run               # make the call

This is the seed shot and nothing more. It does not refine, does not run a
500-example campaign, and does not loop -- it produces one strategy and tells
you whether it is worth running.

Everything is written to report/iterations/ as it happens: the exact prompt,
the raw reply, the extracted module, token usage. That is the "log of how the
strategy evolved" the assignment asks for, and it has to be captured at the
moment of the call because a model reply cannot be reconstructed afterwards.
"""

from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

from dotenv import load_dotenv

from fuzzer.llm import LLM, Budget, BudgetExceeded
from fuzzer.prompts import SYSTEM, seed_prompt
from fuzzer.strategy_io import ExtractionError, extract_code, load_strategy
from fuzzer.validate import validate_strategy

ROOT = Path(__file__).resolve().parents[1]
LOG_DIR = ROOT / "report" / "iterations"
STRATEGY_DIR = ROOT / "fuzzer" / "strategies"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="print the prompt and exit; no API call, no cost")
    parser.add_argument("--model", default=None)
    parser.add_argument("--harness", default=str(ROOT / "build" / "harness"))
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--out", default=str(STRATEGY_DIR / "generated_iter1.py"))
    args = parser.parse_args()

    load_dotenv(ROOT / ".env")
    prompt = seed_prompt()

    if args.dry_run:
        print(prompt)
        print("\n" + "=" * 70)
        print(f"dry run: nothing sent. {len(prompt) + len(SYSTEM)} chars of prompt.")
        return 0

    if not Path(args.harness).exists():
        raise SystemExit(f"no harness at {args.harness} -- run `make` first")

    llm = LLM(model=args.model) if args.model else LLM()
    print(f"model      : {llm.model}")
    print(f"prompt     : {len(prompt)} chars")
    print("calling Vertex ...")

    try:
        response, usage = llm.generate(prompt, system=SYSTEM, temperature=args.temperature)
    except BudgetExceeded as exc:
        raise SystemExit(f"budget: {exc}")

    llm.budget.iterations_used += 1
    print(f"replied    : {usage.output_tokens} output tokens in {usage.seconds:.1f}s")

    LOG_DIR.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    log_path = LOG_DIR / f"iter-01-seed-{stamp}.md"
    log_path.write_text(
        f"# Iteration 1 (seed)\n\n"
        f"- when: {stamp}\n- model: {llm.model}\n"
        f"- temperature: {args.temperature}\n"
        f"- tokens: in {usage.input_tokens}, out {usage.output_tokens}\n\n"
        f"## System\n\n```\n{SYSTEM}\n```\n\n"
        f"## Prompt\n\n```\n{prompt}\n```\n\n"
        f"## Raw response\n\n{response}\n",
        encoding="utf-8",
    )
    print(f"logged     : {log_path.relative_to(ROOT)}")

    try:
        code = extract_code(response)
    except ExtractionError as exc:
        print(f"\nEXTRACTION FAILED: {exc}")
        print(f"the raw reply is in {log_path.relative_to(ROOT)} -- read it before retrying")
        return 1

    out_path = Path(args.out)
    out_path.write_text(
        f'"""Generated by {llm.model} at {stamp}. Do not edit by hand.\n\n'
        f'Iteration 1 (seed). Full prompt and raw reply: {log_path.name}\n"""\n\n'
        + code + "\n",
        encoding="utf-8",
    )
    print(f"strategy   : {out_path.relative_to(ROOT)} ({len(code.splitlines())} lines)")

    try:
        strategy = load_strategy(out_path)
    except ExtractionError as exc:
        print(f"\nLOAD FAILED: {exc}")
        print("the generated module is on disk; read it and see what it did")
        return 1

    print("\nchecking the generator before spending a campaign on it ...\n")
    result = validate_strategy(strategy, args.harness)
    print(result.brief())

    print("\n" + "-" * 70)
    print(llm.budget.report())
    print("-" * 70)

    if result.passed:
        print(
            "\nlooks worth running. Next:\n"
            f"  python -m fuzzer.inspect strategy "
            f"fuzzer.strategies.{out_path.stem}:STRATEGY -n 15"
        )
    else:
        print("\nthe gate refused it -- brief() above is what a refine prompt should react to.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
