"""HAND-PATCHED generated module -- see the note at st_name_well_formed.

Generated by gemini-2.5-flash at 20260902-222938. Do not edit by hand.

Iteration 1 (seed). Full prompt and raw reply: iter-01-seed-20260902-222938.md
"""

import string
from hypothesis import strategies as st

# --- Configuration ---
MAX_DEPTH = 6

# HAND-PATCHED (not model output). The model called _chance(p)
# throughout; st.booleans() accepts no weighting argument. This is the usual
# substitute. The comparison is written so the value shrinks toward False --
# n shrinks to 0, which yields False -- so a minimised reproducer collapses to
# the plainer branch rather than the rarer one.
def _chance(p):
    """A boolean that is True with probability p."""
    return st.integers(min_value=0, max_value=999).map(
        lambda n: n >= 1000 - round(p * 1000)
    )


# Fraction of documents that are intentionally malformed
# This fraction includes various malformation types like mismatched tags, duplicate attributes, etc.
MALFORMED_FRACTION = 0.35

# --- Character and Name Strategies ---

# fragment DIGIT: [0-9];
digits = string.digits
# fragment HEXDIGIT: [a-fA-F0-9];
hexdigits = string.hexdigits

# NameStartChar: [_:a-zA-Z] | '⁰' ..'↏' | ...
# NameChar: NameStartChar | '-' | '.' | DIGIT | '·' | ...
# For practical mxml testing, which may not fully support all Unicode XML name characters,
# we use a robust ASCII-centric set for well-formed names, plus some common Unicode letters.
name_start_chars_base = string.ascii_letters + '_:'
name_chars_base = string.ascii_letters + string.digits + '_-.:'
# Include some common Unicode ranges to test broader character support, without making it too complex
# or generating non-printable characters excessively.
# Examples: Latin-1 Supplement, Latin Extended A, some common symbols.
unicode_name_extensions = "".join(
    chr(i) for i in range(0xC0, 0x300) # Latin-1 Supplement, Latin Extended A, etc.
    if chr(i).isalpha() or chr(i).isdigit() or chr(i) in '_-.'
)
st_name_start_char = st.sampled_from(list(name_start_chars_base + unicode_name_extensions))
st_name_char = st.sampled_from(list(name_chars_base + unicode_name_extensions))

# Name : NameStartChar NameChar*;
# HAND-PATCHED (not model output). The model wrote:
#     (st_name_start_char.map(lambda c: c) + st.text(...)).map(''.join)
# Strategies have no __add__ -- `|` means "either", and there is no operator
# for "both, concatenated". st.tuples(...) is the way to combine them. The
# trailing .map(''.join) it wrote shows it had the right idea.
st_name_well_formed = st.tuples(
    st_name_start_char,
    st.text(st_name_char, min_size=0, max_size=10),
).map(lambda parts: ''.join(parts))

# TEXT: ~[<&]+;
# Any Unicode character except '<' and '&'.
st_text_char = st.characters(blacklist_characters='<&')
st_text = st.text(st_text_char, min_size=1, max_size=50)

# SEA_WS: (' ' | '\t' | '\r'? '\n')+;
st_whitespace_char = st.just(' ') | st.just('\t') | st.just('\n')
st_sea_ws = st.text(st_whitespace_char, min_size=1, max_size=10)

# STRING: '"' ~[<"]* '"' | '\'' ~[<']* '\''
st_dq_string_content = st.text(st.characters(blacklist_characters='<"'), min_size=0, max_size=20)
st_dq_string = st_dq_string_content.map(lambda s: f'"{s}"')
st_sq_string_content = st.text(st.characters(blacklist_characters="<'"), min_size=0, max_size=20)
st_sq_string = st_sq_string_content.map(lambda s: f"'{s}'")
st_string = st_dq_string | st_sq_string

# UNQUOTED_VALUE: ~[ \t\r\n=/><"']+;
_unquoted_value_blacklist = string.whitespace + '=/><"\''
st_unquoted_value_char = st.characters(blacklist_characters=_unquoted_value_blacklist)
st_unquoted_value = st.text(st_unquoted_value_char, min_size=1, max_size=20)

# --- Lexer Tokens (as strategies) ---

# COMMENT : '<!--' .*? '-->';
# Content should not contain '--' to prevent premature closing.
st_comment_content = st.text(st.characters(blacklist_characters='-'), min_size=0, max_size=50)
st_comment = st_comment_content.map(lambda s: f'<!--{s}-->')

# CDATA   : '<![CDATA[' .*? ']]>';
# Content should not contain ']]>' to prevent premature closing.
st_cdata_content = st.text(st.characters(blacklist_characters=']'), min_size=0, max_size=50)
st_cdata = st_cdata_content.map(lambda s: f'<![CDATA[{s}]]>')

# DECLARATION : '<!' .*? '>';
# Content should not contain '>' to prevent premature closing.
st_declaration_content = st.text(st.characters(blacklist_characters='>'), min_size=0, max_size=30)
st_declaration = st_declaration_content.map(lambda s: f'<!{s}>')

# EntityRef : '&' Name ';';
# N3. ENTITY NAMES ARE A CLOSED SET. mxml supports amp, apos, gt, lt, quot.
st_entity_ref_valid_names = st.sampled_from(['amp', 'apos', 'gt', 'lt', 'quot'])
st_entity_ref_valid = st_entity_ref_valid_names.map(lambda n: f'&{n};')

# CharRef : '&#' DIGIT+ ';' | '&#x' HEXDIGIT+ ';';
# Valid codepoints for numeric references (excluding surrogates and non-characters).
st_valid_codepoint = st.integers(min_value=1, max_value=0x10FFFF).filter(
    lambda cp: (0x20 <= cp <= 0x7E) or (cp >= 0xA0 and cp <= 0xD7FF) or (cp >= 0xE000 and cp <= 0xFFFD) or (cp >= 0x10000 and cp <= 0x10FFFF)
).filter(lambda cp: cp not in [0xFFFE, 0xFFFF] and not (0xFDD0 <= cp <= 0xFDEF))

st_char_ref_decimal_valid = st_valid_codepoint.map(lambda i: f'&#{i};')
st_char_ref_hex_valid = st_valid_codepoint.map(lambda i: f'&#x{i:X};')

# Malformed numeric character references
st_char_ref_malformed_val_decimal = st.integers(min_value=-100, max_value=0x110000 + 100).filter(
    lambda i: not (0 <= i <= 0x10FFFF)
).map(lambda i: f'&#{i};')
st_char_ref_malformed_val_hex = st.integers(min_value=-100, max_value=0x110000 + 100).filter(
    lambda i: not (0 <= i <= 0x10FFFF)
).map(lambda i: f'&#x{i:X};')

# Malformed entity reference (unknown entity)
st_entity_ref_unknown = st_name_well_formed.map(lambda n: f'&{n};').filter(
    lambda s: s not in (f'&{name};' for name in ['amp', 'apos', 'gt', 'lt', 'quot'])
)

st_reference_well_formed = st_entity_ref_valid | st_char_ref_decimal_valid | st_char_ref_hex_valid
st_reference_malformed = st_entity_ref_unknown | st_char_ref_malformed_val_decimal | st_char_ref_malformed_val_hex

# Processing Instruction (PI): '<?' Name content '?>'
@st.composite
def st_processing_instruction(draw):
    pi_name = draw(st_name_well_formed)
    # IGNORE_CHAR implies anything can be inside, but avoid '?>' to not prematurely close.
    pi_content = draw(st.text(st.characters(blacklist_characters='?'), min_size=0, max_size=20))
    return f'<?{pi_name} {pi_content}?>'

# --- Parser Rules (Intermediate Strategies) ---

# attribute : Name EQUALS (STRING | UNQUOTED_VALUE | Name)
@st.composite
def st_attribute_value_well_formed(draw):
    return draw(st_string | st_unquoted_value | st_name_well_formed)

@st.composite
def st_attribute_well_formed(draw):
    name = draw(st_name_well_formed)
    value = draw(st_attribute_value_well_formed())
    return f'{name}={value}'

# prolog : XMLDeclOpen attribute* SPECIAL_CLOSE
@st.composite
def st_prolog_well_formed(draw):
    # N2: Ensure attribute names are unique for the prolog too
    unique_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=3))
    attributes = []
    for attr_name in unique_attr_names:
        value = draw(st_attribute_value_well_formed())
        attributes.append(f'{attr_name}={value}')
    attr_str = ' '.join(attributes)
    if attr_str:
        attr_str = ' ' + attr_str
    return f'<?xml{attr_str}?>'

# Define content items that are NOT elements (chardata, reference, CDATA, PI, COMMENT, DECLARATION)
st_non_element_content_item = (
    st_text | st_sea_ws | st_reference_well_formed | st_cdata | st_processing_instruction() | st_comment | st_declaration
)

# Mutual recursion for element and content:
# An element can contain content, and content can contain elements.
st_element_content_item_recursive = st.deferred(lambda: None) # Placeholder for an item in content, including nested elements.
st_element_well_formed_recursive = st.deferred(lambda: None) # Placeholder for the element strategy itself.

# The `element` strategy: self-closing OR contains content.
@st.composite
def _element_builder(draw, children_strategy):
    # children_strategy here is st_element_well_formed_recursive, representing a *nested* element.
    # The content generated for this element can contain `chardata`, `st_non_element_content_item`, or `children_strategy`.

    # N1. OPEN AND CLOSE NAMES MUST MATCH.
    element_name = draw(st_name_well_formed)

    # N2. ATTRIBUTE NAMES MUST BE UNIQUE WITHIN AN ELEMENT.
    unique_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=3))
    attributes = []
    for attr_name in unique_attr_names:
        value = draw(st_attribute_value_well_formed())
        attributes.append(f'{attr_name}={value}')
    attr_str = ' '.join(attributes)
    if attr_str:
        attr_str = ' ' + attr_str

    # Element can be self-closing or have content
    is_self_closing = draw(_chance(0.3))

    if is_self_closing:
        # OPEN Name attribute* SLASH_CLOSE
        return f'<{element_name}{attr_str}/>'
    else:
        # OPEN Name attribute* CLOSE content OPEN SLASH Name CLOSE
        # The content can be mixed and recursive.
        content_parts = []
        # chardata?
        if draw(_chance(0.5)):
            content_parts.append(draw(st_non_element_content_item))
        # ((element | reference | CDATA | PI | COMMENT | DECLARATION) chardata?)*
        # HAND-PATCHED: model wrote max_size=, which integers() does not take.
        num_items = draw(st.integers(min_value=0, max_value=5))
        for _ in range(num_items):
            # An item can be a non-element content item or a nested element (children_strategy)
            content_parts.append(draw(st_non_element_content_item | children_strategy))
            # chardata? after item
            if draw(_chance(0.5)):
                content_parts.append(draw(st_non_element_content_item))
        
        content = ''.join(content_parts)
        return f'<{element_name}{attr_str}>{content}</{element_name}>'

# Set up the actual recursive strategies using the builders and max_depth.
# HAND-PATCHED (not model output): st.recursive takes `max_leaves`, not
# `max_depth`. These bound different things -- max_leaves caps how many base
# cases appear in one value, which limits size and indirectly depth, but does
# not pin depth to 6 the way the model intended. Nesting depth is therefore
# approximate here; worth stating plainly since depth distribution is one of
# the things the loop reports on.
st_element_well_formed_recursive.target = st.recursive(
    # Base case for an element (e.g., a simple self-closing one)
    st.just('<base/>'),
    # Recurser: a function that takes the recursive strategy itself (`children`)
    # and returns a new strategy that can include `children` in its output.
    lambda children: _element_builder(children),
    max_leaves=MAX_DEPTH
)

# --- Document Strategy (Well-formed) ---

# document : prolog? DECLARATION* element SEA_WS? EOF
@st.composite
def st_document_well_formed(draw):
    parts = []
    # prolog?
    if draw(_chance(0.2)):
        parts.append(draw(st_prolog_well_formed()))

    # DECLARATION*
    num_decls = draw(st.integers(min_value=0, max_value=2))
    for _ in range(num_decls):
        parts.append(draw(st_declaration))

    # element (the root element)
    parts.append(draw(st_element_well_formed_recursive.target))

    # SEA_WS? (trailing whitespace)
    if draw(st.booleans()):
        parts.append(draw(st_sea_ws))

    return ''.join(parts)

# --- Malformed Strategies (Near-misses) ---

# A. Mismatched close tag (N1)
@st.composite
def st_element_mismatched_close(draw):
    open_name = draw(st_name_well_formed)
    # Ensure close_name is different from open_name
    # HAND-PATCHED: filter was outside draw(), so it filtered the drawn string.
    close_name = draw(st_name_well_formed.filter(lambda n: n != open_name))
    
    unique_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=3))
    attributes = []
    for attr_name in unique_attr_names:
        value = draw(st_attribute_value_well_formed())
        attributes.append(f'{attr_name}={value}')
    attr_str = ' '.join(attributes)
    if attr_str: attr_str = ' ' + attr_str

    # Content should be well-formed. Since mxml detects mismatched tags at the
    # closing tag, inner content should parse fine.
    content = draw(st_element_well_formed_recursive.target) # Generate an inner valid element for content
    return f'<{open_name}{attr_str}>{content}</{close_name}>'

# B. Duplicate attribute names (N2)
@st.composite
def st_element_duplicate_attribute(draw):
    element_name = draw(st_name_well_formed)
    attr_name = draw(st_name_well_formed) # This name will be duplicated
    val1 = draw(st_attribute_value_well_formed())
    val2 = draw(st_attribute_value_well_formed())

    # Generate other unique attributes
    other_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=2).filter(lambda n: n != attr_name))  # HAND-PATCHED: filter was outside draw()
    other_attrs_list = [f'{n}={draw(st_attribute_value_well_formed())}' for n in other_attr_names]

    attrs_list = [f'{attr_name}={val1}', f'{attr_name}={val2}'] + other_attrs_list
    # HAND-PATCHED: st.shuffled does not exist (st.permutations does), and
    # the drawn value was discarded rather than assigned.
    attrs_list = draw(st.permutations(attrs_list))
    attr_str = ' '.join(attrs_list)
    if attr_str: attr_str = ' ' + attr_str

    is_self_closing = draw(_chance(0.5))
    if is_self_closing:
        return f'<{element_name}{attr_str}/>'
    else:
        content = draw(st_element_well_formed_recursive.target)
        return f'<{element_name}{attr_str}>{content}</{element_name}>'

# C. Unknown entity reference (N3)
@st.composite
def st_document_with_malformed_reference(draw):
    element_name = draw(st_name_well_formed)
    attr_str = ' '.join(draw(st.lists(st_attribute_well_formed(), min_size=0, max_size=1, unique_by=lambda x: x.split('=')[0])))
    if attr_str: attr_str = ' ' + attr_str

    malformed_ref = draw(st_reference_malformed)
    # Surround it with well-formed content to ensure the context is valid.
    # We use `st_element_content_item_recursive.target` to generate diverse inner content.
    prefix_content = draw(st_element_well_formed_recursive.target)
    suffix_content = draw(st_element_well_formed_recursive.target)

    content = f'{prefix_content}{malformed_ref}{suffix_content}'
    return f'<{element_name}{attr_str}>{content}</{element_name}>'

# D. Leading/trailing misc (N4) and other top-level structural errors
@st.composite
def st_document_leading_whitespace(draw):
    ws = draw(st_sea_ws)
    doc = draw(st_document_well_formed())
    return ws + doc

@st.composite
def st_document_leading_misc(draw):
    misc = draw(st_comment | st_cdata | st_processing_instruction())
    doc = draw(st_document_well_formed())
    return misc + doc

@st.composite
def st_document_trailing_misc(draw):
    doc = draw(st_document_well_formed())
    misc = draw(st_comment | st_cdata | st_processing_instruction())
    return doc + misc

# E. Attribute with no value "<a b/>"
@st.composite
def st_element_missing_attribute_value(draw):
    element_name = draw(st_name_well_formed)
    missing_attr_name = draw(st_name_well_formed)
    
    other_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=2).filter(lambda n: n != missing_attr_name))  # HAND-PATCHED: filter was outside draw()
    other_attrs_list = [f'{n}={draw(st_attribute_value_well_formed())}' for n in other_attr_names]

    attrs_list = [missing_attr_name] + other_attrs_list
    # HAND-PATCHED: st.shuffled does not exist (st.permutations does), and
    # the drawn value was discarded rather than assigned.
    attrs_list = draw(st.permutations(attrs_list))
    attr_str = ' '.join(attrs_list)
    if attr_str: attr_str = ' ' + attr_str

    is_self_closing = draw(_chance(0.5))
    if is_self_closing:
        return f'<{element_name}{attr_str}/>'
    else:
        content = draw(st_element_well_formed_recursive.target)
        return f'<{element_name}{attr_str}>{content}</{element_name}>'

# F. Bare < inside tag "<a <b/>"
@st.composite
def st_element_bare_lt_in_tag(draw):
    element_name = draw(st_name_well_formed)
    prefix = draw(st.text(name_chars_base, min_size=0, max_size=5))
    suffix = draw(st.text(name_chars_base, min_size=0, max_size=5))
    # Insert a bare '<' in an attribute list position.
    return f'<{element_name} {prefix}<{suffix}/>'

# G. Truncated comment "<!--x"
st_truncated_comment = st_comment_content.map(lambda s: f'<!--{s}')

# H. Truncated element "<a"
st_truncated_element = st_name_well_formed.map(lambda n: f'<{n}')

# I. Invalid UTF-8 (lone surrogate)
st_lone_surrogate = st.sampled_from([chr(i) for i in range(0xD800, 0xE000)])

@st.composite
def st_text_with_lone_surrogate(draw):
    text_part1 = draw(st.text(st_text_char, min_size=0, max_size=10))
    surrogate = draw(st_lone_surrogate)
    text_part2 = draw(st.text(st_text_char, min_size=0, max_size=10))
    return f'{text_part1}{surrogate}{text_part2}'

@st.composite
def st_document_with_invalid_utf8(draw):
    element_name = draw(st_name_well_formed)
    attr_str = ' '.join(draw(st.lists(st_attribute_well_formed(), min_size=0, max_size=1, unique_by=lambda x: x.split('=')[0])))
    if attr_str: attr_str = ' ' + attr_str
    content_with_surrogate = draw(st_text_with_lone_surrogate())
    return f'<{element_name}{attr_str}>{content_with_surrogate}</{element_name}>'

# J. Raw control characters "<a>\x01</a>"
st_control_char = st.characters(min_codepoint=1, max_codepoint=31).filter(lambda c: c not in '\t\n\r')

@st.composite
def st_text_with_control_char(draw):
    text_part1 = draw(st.text(st_text_char, min_size=0, max_size=10))
    control_char = draw(st_control_char)
    text_part2 = draw(st.text(st_text_char, min_size=0, max_size=10))
    return f'{text_part1}{control_char}{text_part2}'

@st.composite
def st_document_with_control_char(draw):
    element_name = draw(st_name_well_formed)
    attr_str = ' '.join(draw(st.lists(st_attribute_well_formed(), min_size=0, max_size=1, unique_by=lambda x: x.split('=')[0])))
    if attr_str: attr_str = ' ' + attr_str
    content_with_control = draw(st_text_with_control_char())
    return f'<{element_name}{attr_str}>{content_with_control}</{element_name}>'

# K. Empty input ""
st_empty_document = st.just('')

# --- Combining ALL malformed strategies ---
st_malformed_documents = st.one_of(
    st_element_mismatched_close(),
    st_element_duplicate_attribute(),
    st_document_leading_whitespace(),
    st_document_leading_misc(),
    st_document_trailing_misc(),
    st_document_with_malformed_reference(),
    st_element_missing_attribute_value(),
    st_element_bare_lt_in_tag(),
    st_truncated_comment,
    st_truncated_element,
    st_document_with_invalid_utf8(),
    st_document_with_control_char(),
    st_empty_document,
)

# Final STRATEGY combining well-formed and malformed documents
STRATEGY = st.one_of(
    st_document_well_formed(),
    _chance(MALFORMED_FRACTION).flatmap(
        lambda is_malformed: st_malformed_documents if is_malformed else st_document_well_formed()
    )
)
