"""Generated (refine iteration 5) at 20260904-222146. Do not edit by hand."""

"""HAND-PATCHED generated module -- see the note at st_name_well_formed.

Generated by gemini-2.5-flash at 20260902-222938. Do not edit by hand.

Iteration 1 (seed). Full prompt and raw reply: iter-01-seed-20260902-222938.md
"""

import string
from hypothesis import strategies as st

# --- Configuration ---
# MAX_DEPTH controls max_leaves in st.recursive, which affects the maximum number of base-case elements.
# A higher value encourages more nodes in the tree, leading to more complex documents.
# Increased from 50 to 200 to encourage deeper nesting, as previous iteration showed 79% depth 0.
MAX_DEPTH = 200

# HAND-PATCHED (not model output). The model called _chance(p)
# throughout; st.booleans() accepts no weighting argument. This is the usual
# substitute. The comparison is written so the value shrinks toward False --
# n shrinks to 0, which yields False -- so a minimised reproducer collapses to
# the plainer branch rather than the rarer one.
def _chance(p):
    """A boolean that is True with probability p."""
    # hypothesis.reject() might not work in all contexts, use st.integers for a deterministic weighted choice.
    return st.integers(min_value=0, max_value=999).map(
        lambda n: n >= 1000 - round(p * 1000)
    )


# Fraction of documents that are intentionally malformed
# Adjusted based on observed acceptance rate (92.6% was too high).
# Aim for 70-85% acceptance, so 15-30% rejection. A MALFORMED_FRACTION of 0.35
# means 35% of documents will be chosen from st_malformed_documents.
# Given that some "malformed" documents are actually accepted by mxml (e.g., control chars),
# this fraction should bring the true rejection rate into the target band.
MALFORMED_FRACTION = 0.35

# --- Character and Name Strategies ---

# fragment DIGIT: [0-9];
digits = string.digits
# fragment HEXDIGIT: [a-fA-F0-9];
hexdigits = string.hexdigits

# NameStartChar: [_:a-zA-Z] | '⁰' ..'↏' | ...
# NameChar: NameStartChar | '-' | '.' | DIGIT | '·' | ...
# For practical mxml testing, which may not fully support all Unicode XML name characters,
# we use a robust ASCII-centric set for well-formed names, plus some common Unicode letters.
name_start_chars_base = string.ascii_letters + '_:'
name_chars_base = string.ascii_letters + string.digits + '_-.:'
# Include some common Unicode ranges to test broader character support, without making it too complex
# or generating non-printable characters excessively.
# Examples: Latin-1 Supplement, Latin Extended A, some common symbols.
unicode_name_extensions = "".join(
    chr(i) for i in range(0xC0, 0x300) # Latin-1 Supplement, Latin Extended A, etc.
    if chr(i).isalpha() or chr(i).isdigit() or chr(i) in '_-.'
)
st_name_start_char = st.sampled_from(list(name_start_chars_base + unicode_name_extensions))
st_name_char = st.sampled_from(list(name_chars_base + unicode_name_extensions))

# Name : NameStartChar NameChar*;
# HAND-PATCHED (not model output). The model wrote:
#     (st_name_start_char.map(lambda c: c) + st.text(...)).map(''.join)
# Strategies have no __add__ -- `|` means "either", and there is no operator
# for "both, concatenated". st.tuples(...) is the way to combine them. The
# trailing .map(''.join) it wrote shows it had the right idea.
st_name_well_formed = st.tuples(
    st_name_start_char,
    st.text(st_name_char, min_size=0, max_size=10),
).map(lambda parts: ''.join(parts))

# Base strategy for characters valid in XML 1.0 (excluding control characters, surrogates, FFFE/FFFF, NULL)
# These are the characters allowed in XML documents.
_st_xml_base_char = (
    st.characters(min_codepoint=0x20, max_codepoint=0x10FFFF) # Excludes most ASCII control characters
    .filter(lambda c: c not in '\x00') # Explicitly exclude NULL
    .filter(lambda c: not (0xD800 <= ord(c) <= 0xDFFF)) # Exclude surrogates
    .filter(lambda c: not (0xFFFE <= ord(c) <= 0xFFFF)) # Exclude non-characters FFFE/FFFF
    | st.sampled_from(['\t', '\n', '\r']) # Explicitly allow TAB, LF, CR
)

# TEXT: ~[<&]+;
# Any valid XML character except '<' and '&'.
st_text_char = _st_xml_base_char.filter(lambda c: c not in '<&')
st_text = st.text(st_text_char, min_size=1, max_size=50)

# SEA_WS: (' ' | '\t' | '\r'? '\n')+;
st_whitespace_char = st.just(' ') | st.just(' ') | st.just('\n') # Corrected: previously ' ' | '\t' | '\n'
st_sea_ws = st.text(st_whitespace_char, min_size=1, max_size=10)

# STRING: '"' ~[<"]* '"' | '\'' ~[<']* '\''
st_dq_string_content_char = _st_xml_base_char.filter(lambda c: c not in '<"')
st_dq_string_content = st.text(st_dq_string_content_char, min_size=0, max_size=20)
st_dq_string = st_dq_string_content.map(lambda s: f'"{s}"')

st_sq_string_content_char = _st_xml_base_char.filter(lambda c: c not in "<'")
st_sq_string_content = st.text(st_sq_string_content_char, min_size=0, max_size=20)
st_sq_string = st_sq_string_content.map(lambda s: f"'{s}'")
st_string = st_dq_string | st_sq_string

# UNQUOTED_VALUE: ~[ \t\r\n=/><"']+;
_unquoted_value_blacklist = string.whitespace + '=/><"\''
st_unquoted_value_char = _st_xml_base_char.filter(lambda c: c not in _unquoted_value_blacklist)
st_unquoted_value = st.text(st_unquoted_value_char, min_size=1, max_size=20)

# --- Lexer Tokens (as strategies) ---

# COMMENT : '<!--' .*? '-->';
# Content should not contain '--' to prevent premature closing.
st_comment_char = _st_xml_base_char.filter(lambda c: c != '-')
st_comment_content = st.text(st_comment_char, min_size=0, max_size=50)
st_comment = st_comment_content.map(lambda s: f'<!--{s}-->')

# CDATA   : '<![CDATA[' .*? ']]>';
# Content should not contain ']]>' to prevent premature closing.
st_cdata_char = _st_xml_base_char.filter(lambda c: c != ']')
st_cdata_content = st.text(st_cdata_char, min_size=0, max_size=50)
st_cdata = st_cdata_content.map(lambda s: f'<![CDATA[{s}]]>')

# DECLARATION : '<!' .*? '>';
# Content should not contain '>' to prevent premature closing.
st_declaration_char = _st_xml_base_char.filter(lambda c: c != '>')
st_declaration_content = st.text(st_declaration_char, min_size=0, max_size=30)
st_declaration = st_declaration_content.map(lambda s: f'<!{s}>')

# EntityRef : '&' Name ';';
# N3. ENTITY NAMES ARE A CLOSED SET. mxml supports amp, apos, gt, lt, quot.
st_entity_ref_valid_names = st.sampled_from(['amp', 'apos', 'gt', 'lt', 'quot'])
st_entity_ref_valid = st_entity_ref_valid_names.map(lambda n: f'&{n};')

# CharRef : '&#' DIGIT+ ';' | '&#x' HEXDIGIT+ ';';
# Valid codepoints for numeric references (excluding surrogates and non-characters).
st_valid_codepoint = st.integers(min_value=1, max_value=0x10FFFF).filter(
    lambda cp: (0x20 <= cp <= 0x7E) or (cp >= 0xA0 and cp <= 0xD7FF) or (cp >= 0xE000 and cp <= 0xFFFD) or (cp >= 0x10000 and cp <= 0x10FFFF)
).filter(lambda cp: cp not in [0xFFFE, 0xFFFF] and not (0xFDD0 <= cp <= 0xFDEF)) # Excludes PUA non-characters

st_char_ref_decimal_valid = st_valid_codepoint.map(lambda i: f'&#{i};')
st_char_ref_hex_valid = st_valid_codepoint.map(lambda i: f'&#x{i:X};')

# Malformed numeric character references (invalid range)
st_char_ref_malformed_val_decimal = st.integers(min_value=-100, max_value=0x110000 + 100).filter(
    lambda i: not (0 <= i <= 0x10FFFF)
).map(lambda i: f'&#{i};')
st_char_ref_malformed_val_hex = st.integers(min_value=-100, max_value=0x110000 + 100).filter(
    lambda i: not (0 <= i <= 0x10FFFF)
).map(lambda i: f'&#x{i:X};')

# Malformed entity reference (unknown entity name)
st_entity_ref_unknown = st_name_well_formed.map(lambda n: f'&{n};').filter(
    lambda s: s not in (f'&{name};' for name in ['amp', 'apos', 'gt', 'lt', 'quot'])
)

# NEW: Malformed entity/character reference (unterminated - missing semicolon)
@st.composite
def st_reference_unterminated(draw):
    ref_type = draw(st.sampled_from(['named', 'decimal', 'hex']))
    if ref_type == 'named':
        name = draw(st_name_well_formed)
        return f'&{name}'
    elif ref_type == 'decimal':
        val = draw(st.integers(min_value=1, max_value=0x10FFFF))
        return f'&#{val}'
    else: # hex
        val = draw(st.integers(min_value=1, max_value=0x10FFFF))
        return f'&#x{val:X}'


st_reference_well_formed = st_entity_ref_valid | st_char_ref_decimal_valid | st_char_ref_hex_valid
st_reference_malformed = (
    st_entity_ref_unknown
    | st_char_ref_malformed_val_decimal
    | st_char_ref_malformed_val_hex
)

# Processing Instruction (PI): '<?' Name content '?>'
@st.composite
def st_processing_instruction(draw):
    pi_name = draw(st_name_well_formed)
    # Content should not contain '?>' to prevent premature closing.
    # mxml's documentation states content cannot contain "?>"
    st_pi_content_char = _st_xml_base_char.filter(lambda c: c != '?') # Avoid '?' to prevent '?>'
    pi_content_str = draw(st.text(st_pi_content_char, min_size=0, max_size=20).map(lambda s: s.replace('?>', '')))
    return f'<?{pi_name} {pi_content_str}?>'

# --- Parser Rules (Intermediate Strategies) ---

# attribute : Name EQUALS (STRING | UNQUOTED_VALUE | Name)
@st.composite
def st_attribute_value_well_formed(draw):
    return draw(st_string | st_unquoted_value | st_name_well_formed)

@st.composite
def st_attribute_well_formed(draw):
    name = draw(st_name_well_formed)
    value = draw(st_attribute_value_well_formed())
    return f'{name}={value}'

# prolog : XMLDeclOpen attribute* SPECIAL_CLOSE
@st.composite
def st_prolog_well_formed(draw):
    # N2: Ensure attribute names are unique for the prolog too
    unique_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=3))
    attributes = []
    for attr_name in unique_attr_names:
        value = draw(st_attribute_value_well_formed())
        attributes.append(f'{attr_name}={value}')
    attr_str = ' '.join(attributes)
    if attr_str:
        attr_str = ' ' + attr_str
    return f'<?xml{attr_str}?>'

# Define content items that are NOT elements (chardata, reference, CDATA, PI, COMMENT, DECLARATION)
st_non_element_content_item = (
    st_text | st_sea_ws | st_reference_well_formed | st_cdata | st_processing_instruction() | st_comment | st_declaration
)

# Mutual recursion for element and content:
# An element can contain content, and content can contain elements.
st_element_content_item_recursive = st.deferred(lambda: None) # Placeholder for an item in content, including nested elements.
st_element_well_formed_recursive = st.deferred(lambda: None) # Placeholder for the element strategy itself.

# Helper for element start tags and attributes (used by leaf and recursive elements)
@st.composite
def _element_start_tag_and_attrs(draw):
    element_name = draw(st_name_well_formed)
    # N2. ATTRIBUTE NAMES MUST BE UNIQUE WITHIN AN ELEMENT.
    unique_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=3))
    attributes = []
    for attr_name in unique_attr_names:
        value = draw(st_attribute_value_well_formed())
        attributes.append(f'{attr_name}={value}')
    attr_str = ' '.join(attributes)
    if attr_str:
        attr_str = ' ' + attr_str
    return element_name, attr_str

# Base case for st.recursive: an element that does not contain other elements.
# This can be self-closing or contain only non-element content.
@st.composite
def st_element_leaf(draw):
    element_name, attr_str = draw(_element_start_tag_and_attrs())
    
    # 50% chance of being self-closing, 50% chance of having non-element content
    if draw(_chance(0.5)):
        # OPEN Name attribute* SLASH_CLOSE
        return f'<{element_name}{attr_str}/>'
    else:
        # OPEN Name attribute* CLOSE (non-element content) OPEN SLASH Name CLOSE
        num_content_items = draw(st.integers(min_value=1, max_value=5)) # At least one content item
        content_parts = [draw(st_non_element_content_item) for _ in range(num_content_items)]
        content = ''.join(content_parts)
        return f'<{element_name}{attr_str}>{content}</{element_name}>'

# Extend case for st.recursive: an element that contains other elements (children).
@st.composite
def st_element_with_children(draw, child_element_strategy):
    # child_element_strategy here is st_element_well_formed_recursive.target,
    # which can resolve to either st_element_leaf() or another st_element_with_children().
    element_name, attr_str = draw(_element_start_tag_and_attrs())
    
    content_parts = []
    # Ensure at least one child element to drive nesting, up to 3.
    num_child_elements = draw(st.integers(min_value=1, max_value=3))
    for _ in range(num_child_elements):
        # Interleave child elements with optional non-element content
        if draw(_chance(0.5)): # 50% chance of non-element content before child
            content_parts.append(draw(st_non_element_content_item))
        content_parts.append(draw(child_element_strategy)) # Recursive call for a child element
        if draw(_chance(0.5)): # 50% chance of non-element content after child
            content_parts.append(draw(st_non_element_content_item))

    # Add optional leading/trailing non-element content for more variety
    if draw(_chance(0.3)):
        content_parts.insert(0, draw(st_non_element_content_item))
    if draw(_chance(0.3)):
        content_parts.append(draw(st_non_element_content_item))
    
    # HAND-PATCHED: Corrected shuffling. st.randoms() returns a random object, not a strategy.
    # Use st.permutations to shuffle a list of drawn items.
    content_parts = draw(st.permutations(content_parts))
    content = ''.join(content_parts)
    return f'<{element_name}{attr_str}>{content}</{element_name}>'

# Set up the actual recursive strategies using the builders and max_depth.
# HAND-PATCHED (not model output): st.recursive takes `max_leaves`, not
# `max_depth`. These bound different things -- max_leaves caps how many base
# cases appear in one value, which limits size and indirectly depth, but does
# not pin depth to 6 the way the model intended. Nesting depth is therefore
# approximate here; worth stating plainly since depth distribution is one of
# the things the loop reports on.
st_element_well_formed_recursive.target = st.recursive(
    st_element_leaf(), # Base case: an element that does not recursively contain other elements
    st_element_with_children, # Extender: an element that contains other elements (recursive step)
    max_leaves=MAX_DEPTH # MAX_DEPTH increased to 200 for deeper and wider trees
)

# --- Document Strategy (Well-formed) ---

# document : prolog? DECLARATION* element SEA_WS? EOF
@st.composite
def st_document_well_formed(draw):
    parts = []
    # prolog?
    if draw(_chance(0.2)):
        parts.append(draw(st_prolog_well_formed()))

    # DECLARATION*
    num_decls = draw(st.integers(min_value=0, max_value=2))
    for _ in range(num_decls):
        parts.append(draw(st_declaration))

    # element (the root element)
    parts.append(draw(st_element_well_formed_recursive.target))

    # SEA_WS? (trailing whitespace)
    if draw(st.booleans()):
        parts.append(draw(st_sea_ws))

    return ''.join(parts)

# --- Malformed Strategies (Near-misses) ---

# A. Mismatched close tag (N1)
@st.composite
def st_element_mismatched_close(draw):
    open_name = draw(st_name_well_formed)
    # Ensure close_name is different from open_name
    close_name = draw(st_name_well_formed.filter(lambda n: n != open_name))
    
    element_name, attr_str = draw(_element_start_tag_and_attrs()) # Reuse attribute logic

    # Content should be well-formed. Since mxml detects mismatched tags at the
    # closing tag, inner content should parse fine.
    content = draw(st_element_well_formed_recursive.target) # Generate an inner valid element for content
    return f'<{element_name}{attr_str}>{content}</{close_name}>'

# B. Duplicate attribute names (N2)
@st.composite
def st_element_duplicate_attribute(draw):
    element_name = draw(st_name_well_formed)
    attr_name = draw(st_name_well_formed) # This name will be duplicated
    val1 = draw(st_attribute_value_well_formed())
    val2 = draw(st_attribute_value_well_formed())

    # Generate other unique attributes
    other_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=2).filter(lambda n: n != attr_name))
    other_attrs_list = [f'{n}={draw(st_attribute_value_well_formed())}' for n in other_attr_names]

    attrs_list = [f'{attr_name}={val1}', f'{attr_name}={val2}'] + other_attrs_list
    attrs_list = draw(st.permutations(attrs_list))
    attr_str = ' '.join(attrs_list)
    if attr_str: attr_str = ' ' + attr_str

    # Use element leaf strategy to avoid infinite recursion while introducing malformation
    # We still want to test the duplicate attribute on various elements (self-closing or with content)
    is_self_closing = draw(_chance(0.5))
    if is_self_closing:
        return f'<{element_name}{attr_str}/>'
    else:
        content = draw(st_element_leaf()) # Use leaf strategy for simpler content
        return f'<{element_name}{attr_str}>{content}</{element_name}>'

# C. Unknown entity reference or malformed numeric references (N3)
@st.composite
def st_document_with_malformed_reference(draw):
    element_name, attr_str = draw(_element_start_tag_and_attrs())
    
    # st_reference_malformed now combines unknown names and invalid numeric ranges
    malformed_ref = draw(st_reference_malformed)
    # Surround it with well-formed content to ensure the context is valid.
    # Use st_text to get simple content, as embedding complex elements with malformed ref might hide the specific error.
    prefix_content = draw(st.text(st_text_char, min_size=0, max_size=10))
    suffix_content = draw(st.text(st_text_char, min_size=0, max_size=10))

    content = f'{prefix_content}{malformed_ref}{suffix_content}'
    return f'<{element_name}{attr_str}>{content}</{element_name}>'

# D. Leading/trailing comments/CDATA/PI before/after the root element (mxml rejects these)
@st.composite
def st_document_around_misc(draw):
    doc = draw(st_document_well_formed())
    misc_item = draw(st_comment | st_cdata | st_processing_instruction())
    
    if draw(st.booleans()): # Leading misc
        return misc_item + doc
    else: # Trailing misc
        return doc + misc_item

# E. Leading whitespace (mxml rejects this for the very first byte)
@st.composite
def st_document_leading_whitespace(draw):
    ws = draw(st_sea_ws)
    doc = draw(st_document_well_formed())
    return ws + doc

# F. Attribute with no value "<a b/>"
@st.composite
def st_element_missing_attribute_value(draw):
    element_name = draw(st_name_well_formed)
    missing_attr_name = draw(st_name_well_formed)
    
    other_attr_names = draw(st.sets(st_name_well_formed, min_size=0, max_size=2).filter(lambda n: n != missing_attr_name))
    other_attrs_list = [f'{n}={draw(st_attribute_value_well_formed())}' for n in other_attr_names]

    attrs_list = [missing_attr_name] + other_attrs_list # The attribute with no value
    attrs_list = draw(st.permutations(attrs_list))
    attr_str = ' '.join(attrs_list)
    if attr_str: attr_str = ' ' + attr_str

    is_self_closing = draw(_chance(0.5))
    if is_self_closing:
        return f'<{element_name}{attr_str}/>'
    else:
        content = draw(st_element_leaf()) # Use leaf strategy for simpler content
        return f'<{element_name}{attr_str}>{content}</{element_name}>'

# G. Bare < inside tag "<a <b/>"
@st.composite
def st_element_bare_lt_in_tag(draw):
    element_name = draw(st_name_well_formed)
    prefix = draw(st.text(name_chars_base, min_size=0, max_size=5))
    suffix = draw(st.text(name_chars_base, min_size=0, max_size=5))
    # Insert a bare '<' in an attribute list position.
    return f'<{element_name} {prefix}<{suffix}/>'

# H. Truncated comment "<!--x"
st_truncated_comment = st_comment_content.map(lambda s: f'<!--{s}')

# I. Empty input ""
st_empty_document = st.just('')

# J. Invalid UTF-8 (lone surrogate)
_st_lone_surrogate = st.integers(min_value=0xD800, max_value=0xDFFF).map(chr)
@st.composite
def st_document_with_invalid_utf8(draw):
    element_name, attr_str = draw(_element_start_tag_and_attrs())
    
    pre_text = draw(st.text(st_text_char, min_size=0, max_size=10))
    lone_surrogate = draw(_st_lone_surrogate)
    post_text = draw(st.text(st_text_char, min_size=0, max_size=10))
    
    content = f'{pre_text}{lone_surrogate}{post_text}'
    return f'<{element_name}{attr_str}>{content}</{element_name}>'

# K. Unclosed element with content (e.g., <foo>text)
# This can lead to "Early EOF" or "no message" errors.
@st.composite
def st_element_unterminated_with_content(draw):
    element_name = draw(st_name_well_formed)
    _, attr_str = draw(_element_start_tag_and_attrs()) # Reuse attribute logic, discard element_name
    
    # Generate some well-formed content
    num_content_items = draw(st.integers(min_value=1, max_value=5))
    content_parts = [draw(st_non_element_content_item) for _ in range(num_content_items)]
    content = ''.join(content_parts)
    
    return f'<{element_name}{attr_str}>{content}'


# --- Removed from malformed as they are accepted or silently parsed ---
# These cases, while "malformed" by strict XML spec, are ACCEPTED by mxml
# (either silently or with a diagnostic but still producing a tree).
# Including them in `st_malformed_documents` led to an artificially high
# acceptance rate for the "malformed" bucket.

# Previously: K. Control Character (non-whitespace ASCII control char) - ACCEPTED with diagnostic
# _st_control_char_non_whitespace = st.sampled_from([chr(i) for i in range(0x01, 0x20) if i not in (0x09, 0x0A, 0x0D)])
# @st.composite
# def st_document_with_control_char(draw):
#     element_name, attr_str = draw(_element_start_tag_and_attrs())
#     pre_text = draw(st.text(st_text_char, min_size=0, max_size=10))
#     control_char = draw(_st_control_char_non_whitespace)
#     post_text = draw(st.text(st_text_char, min_size=0, max_size=10))
#     content = f'{pre_text}{control_char}{post_text}'
#     return f'<{element_name}{attr_str}>{content}</{element_name}>'

# Previously: H. Truncated element "<a" - ACCEPTED silently
# st_truncated_element = st_name_well_formed.map(lambda n: f'<{n}')


# --- Combining ALL malformed strategies that lead to REJECTION ---
st_malformed_documents = st.one_of(
    st_element_mismatched_close(),
    st_element_duplicate_attribute(),
    st_document_leading_whitespace(),
    st_document_around_misc(),
    st_document_with_malformed_reference(),
    st_reference_unterminated(),
    st_element_missing_attribute_value(),
    st_element_bare_lt_in_tag(),
    st_truncated_comment,
    st_empty_document,
    st_document_with_invalid_utf8(),
    st_element_unterminated_with_content(), # New malformed strategy
)

# Final STRATEGY combining well-formed and malformed documents with a precise weighting.
# The _chance(MALFORMED_FRACTION) directly controls the probability of a malformed document.
@st.composite
def _main_strategy_weighted_choice(draw):
    if draw(_chance(MALFORMED_FRACTION)):
        return draw(st_malformed_documents)
    else:
        return draw(st_document_well_formed())

STRATEGY = _main_strategy_weighted_choice()
